version: '3.8'

services:

  backend:
    image: ecl1ps0/chatapp-backend:latest
    deploy:
      placement:
        constraints: [node.hostname == ip-172-31-24-209]

  nginx:
    image: ecl1ps0/chatapp-frontend:latest
    deploy:
      placement:
        constraints: [node.hostname == ip-172-31-28-101]
    ports:
      - "80:80"
