version: '3.8'

services:

  backend:
    image: ecl1ps0/chatapp-backend:latest
    environment:
      - MONGO_URI=mongodb+srv://admin:rKLDYu4JQgtffI0W@chatapp.j4ybl.mongodb.net/?retryWrites=true&w=majority&appName=ChatApp
      - SIGN_KEY=itISaSECRET
    deploy:
      placement:
        constraints:
          - node.labels.role == backend

  nginx:
    image: ecl1ps0/chatapp-frontend:latest
    deploy:
      placement:
        constraints: [node.hostname == ip-172-31-28-101]
    ports:
      - "80:80"
