name: CI/CD Pipeline for CRUD App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Show current working directory
        run: pwd

      - name: Build and Push Docker Images
        run: |
          docker build --build-arg VITE_DOMAIN_HTTPS=http://16.171.65.117 --build-arg VITE_DOMAIN_WSS=ws://16.171.65.117 -t ${{ secrets.DOCKER_USER }}/chatapp-frontend ./chat-app-frontend --progress=plain
          docker build -t ${{ secrets.DOCKER_USER }}/chatapp-backend .
          docker push ${{ secrets.DOCKER_USER }}/chatapp-frontend
          docker push ${{ secrets.DOCKER_USER }}/chatapp-backend

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MANAGER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/home/ubuntu/deploy"

      - name: SSH to Manager and Deploy Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MANAGER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/deploy
            docker stack deploy -c docker-compose.yml chatapp
