name: CI/CD Pipeline for CRUD App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Show current working directory
        run: pwd

      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/chatapp-frontend ./frontend
          docker build -t ${{ secrets.DOCKER_USER }}/chatapp-backend ./backend
          docker push ${{ secrets.DOCKER_USER }}/chatapp-frontend
          docker push ${{ secrets.DOCKER_USER }}/chatapp-backend

      - name: SSH to Manager and Deploy Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MANAGER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/deploy
            docker stack deploy -c docker-compose.yml chatapp
